import type { Metadata } from "next";
import { Aside } from "@/shared/components/layout/Aside";
import "@/app/globals.css";
import { Footer } from "@/shared/components/layout/Footer/Footer";

export const metadata: Metadata = {
    title: "PizzaStack",
    description: "Generated by create next app",
    icons: {
        icon: [
            { url: "/favicon.ico" },
            { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
            { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
        ],
        apple: [{ url: "/apple-touch-icon.png" }],
    },
    manifest: "/site.webmanifest",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <main>
                <Aside />
                {children}
            </main>
            
            <Footer isAdmin={true} />
        </>
                
    );
}
